#!/usr/bin/env python3

import random
from tkinter import *
import pygame
from tkinter.font import *

# -- GLOBAL VARIABLES -- #

roles = {"Loup Garou": True, "Loup Garou blanc": True, "Grand méchant loup": False, "Infect père des loups": True, "Loup amnésique": True, "Simple villageois": True, "Voyante": True, "Chasseur": True, "Cupidon": True, "Sorcière": True, "Petite fille": True, "Voleur": True, "Salvateur": True, "Idiot du village": True, "Bouc émissaire": True, "Ancien": True, "Joueur de flûte": True, "Corbeau": True, "Enfant sauvage": True, "Renard": True, "Soeur": True, "Montreur d'ours": True, "Chien loup": True, "Chevalier à l'épée rouillée": True}

# ---------------------- #

class Game(object):

    player_list = []
    player_roles = {}
    game_info = {"Couple": [], "Loups": [], "Enchantés": [], "Maitre": "NULL", "Modèle": "NULL", "Protected": "NULL", "Soeurs": []}

    fenetre = 0

    window = Tk()
    font_title = Font(root=window, family="Times", size=24, weight="bold", slant="italic")
    font_copyright = Font(root=window, family="Times", size=8, slant="italic")
    font_options = Font(root=window, family="Times", size=15, slant="italic")

    def __init__(self):
        self.window.title("Loup Garou 1.0")
        self.window.geometry("1200x800+150+150")
        self.window.resizable(0, 0)

        self.main_menu()

        self.window.mainloop()

    def main_menu(self):
        for c in self.window.winfo_children():
            c.destroy()

        title = Label(self.window, text="Loup Garou", font=self.font_title, fg="red")
        launch = Button(self.window, text="Jouer", command=self.play_menu)
        options = Button(self.window, text="Options", command=self.options_menu)
        leave = Button(self.window, text="Quitter", command=self.window.destroy)
        cpyright = Label(self.window, text="© 2019 Cyril Grosjean", font=self.font_copyright, fg="grey")

        title.place(x=520, y=10)
        launch.place(x=420, y=200, width=400, height=40)
        options.place(x=420, y=300, width=400, height=40)
        leave.place(x=420, y=400, width=400, height=40)
        cpyright.place(x=5, y=780)

    def play_menu(self):
        pass

    def options_menu(self):
        global roles

        for c in self.window.winfo_children():
            c.destroy()

        compo_list = []
        for i in roles.keys():
            compo_list.append(i)
        del compo_list[compo_list.index("Simple villageois")]
        del compo_list[compo_list.index("Loup Garou")]
        title = Label(self.window, text="Loup Garou", font=self.font_title, fg="red")

        self.select_roles_var = StringVar()
        self.select_roles_var.set("Loup Garou blanc")
        select_roles = OptionMenu(self.window, self.select_roles_var, *compo_list, command=self.toggle_label_func)
        toggle_button = Button(self.window, text="Activer / Désactiver", command=self.toggle_role)
        self.toggle_label = Label(self.window, text="Activé", fg="green", font=self.font_options)

        title.place(x=520, y=10)
        select_roles.place(x=50, y=100, width=300, height=40)
        self.toggle_label.place(x=150, y=150)
        toggle_button.place(x=360, y=100, width=200, height=40)

    def toggle_role(self):
        global roles

        if roles.get(self.select_roles_var.get()):
            self.toggle_label.config(text="Désactivé", fg="red")
            roles[self.select_roles_var.get()] = False
        else:
            self.toggle_label.config(text="Activé", fg="green")
            roles[self.select_roles_var.get()] = True

    def toggle_label_func(self, event):
        global roles

        if roles.get(self.select_roles_var.get()):
            self.toggle_label.config(text="Activé", fg="green")
        else:
            self.toggle_label.config(text="Désactivé", fg="red")


Game()