#!/usr/bin/env python3

import random
from tkinter import *
import pygame
from tkinter.font import *

# -- GLOBAL VARIABLES -- #

roles = {"Loup Garou": True, "Loup Garou blanc": True, "Grand méchant loup": False, "Infect père des loups": True, "Loup amnésique": True, "Simple villageois": True, "Voyante": True, "Chasseur": True, "Cupidon": True, "Sorcière": True, "Petite fille": True, "Voleur": True, "Salvateur": True, "Idiot du village": True, "Bouc émissaire": True, "Ancien": True, "Joueur de flûte": True, "Corbeau": True, "Enfant sauvage": True, "Renard": True, "Soeur": True, "Montreur d'ours": True, "Chien loup": True, "Chevalier à l'épée rouillée": True}

# ---------------------- #

class Game(object):

    player_list = []
    player_roles = {}
    game_info = {"Couple": [], "Loups": [], "Enchantés": [], "Maitre": "NULL", "Modèle": "NULL", "Protected": "NULL", "Soeurs": []}

    fenetre = 0

    window = Tk()
    font_title = Font(root=window, family="Times", size=24, weight="bold", slant="italic")
    font_copyright = Font(root=window, family="Times", size=8, slant="italic")
    font_options = Font(root=window, family="Times", size=15, slant="italic")

    def __init__(self):
        self.window.title("Loup Garou 1.0")
        self.window.geometry("1200x800+150+150")
        self.window.resizable(0, 0)

        self.main_menu()

        self.window.mainloop()

    def main_menu(self):
        for c in self.window.winfo_children():
            c.destroy()

        title = Label(self.window, text="Loup Garou", font=self.font_title, fg="red")
        launch = Button(self.window, text="Jouer", command=self.play_menu)
        options = Button(self.window, text="Options", command=self.options_menu)
        leave = Button(self.window, text="Quitter", command=self.window.destroy)
        cpyright = Label(self.window, text="© 2019 Cyril Grosjean", font=self.font_copyright, fg="grey")

        title.place(x=520, y=10)
        launch.place(x=420, y=200, width=400, height=40)
        options.place(x=420, y=300, width=400, height=40)
        leave.place(x=420, y=400, width=400, height=40)
        cpyright.place(x=5, y=780)

    def play_menu(self):
        pass

    def options_menu(self):
        global roles

        for c in self.window.winfo_children():
            c.destroy()

        compo_list = []
        for i in roles.keys():
            compo_list.append(i)
        del compo_list[compo_list.index("Simple villageois")]
        del compo_list[compo_list.index("Loup Garou")]
        title = Label(self.window, text="Loup Garou", font=self.font_title, fg="red")

        # - Activer / Désactiver rôles

        self.select_roles_var = StringVar()
        self.select_roles_var.set("Loup Garou blanc")
        select_roles = OptionMenu(self.window, self.select_roles_var, *compo_list, command=self.toggle_label_func)
        toggle_button = Button(self.window, text="Activer / Désactiver", command=self.toggle_role)
        self.toggle_label = Label(self.window, text="Activé", fg="green", font=self.font_options)

        # - Voyante bavarde ou non + chances de bavardage

        self.voy_bavarde_var = IntVar()
        self.voy_bavarde_var.set(0)
        voy_bavarde = Checkbutton(self.window, text="Voyante bavarde", variable=self.voy_bavarde_var)
        luck_bavar_label = Label(self.window, text="Chances de bavardage (en %)")
        self.luck_bavar = Spinbox(self.window, from_=0, to=100)

        # - Type de couple

        self.couple_var = StringVar()
        self.couple_var.set("Couple classique")
        couple = OptionMenu(self.window, self.couple_var, "Couple classique", "Couple composé du cupidon", "Couple aléatoire", "Pas de couple")
        couple_label = Label(self.window, text="Type de couple")

        # - Taux de réveil du LGB

        lgb_label = Label(self.window, text="Réveil du Loup Garou Blanc")
        self.taux_lgb = Spinbox(self.window, from_=1, to=5, command=self.toggle_lgb_taux)
        self.lgb_label1 = Label(self.window, text="Toutes les 1 nuit(s)")

        # - 

        title.place(x=520, y=10)
        select_roles.place(x=50, y=100, width=300, height=40)
        self.toggle_label.place(x=150, y=150)
        toggle_button.place(x=360, y=100, width=200, height=40)
        voy_bavarde.place(x=600, y=110)
        luck_bavar_label.place(x=800, y=100)
        self.luck_bavar.place(x=800, y=125)
        couple_label.place(x=150, y=200)
        couple.place(x=50, y=230, width=300, height=40)
        lgb_label.place(x=450, y=200)
        self.taux_lgb.place(x=450, y=230)
        self.lgb_label1.place(x=470, y=260)

    def toggle_lgb_taux(self):
        self.lgb_label1.config(text="Toutes les " + str(self.taux_lgb.get()) + " nuit(s)")

    def toggle_role(self):
        global roles

        if roles.get(self.select_roles_var.get()):
            self.toggle_label.config(text="Désactivé", fg="red")
            roles[self.select_roles_var.get()] = False
        else:
            self.toggle_label.config(text="Activé", fg="green")
            roles[self.select_roles_var.get()] = True

    def toggle_label_func(self, event):
        global roles

        if roles.get(self.select_roles_var.get()):
            self.toggle_label.config(text="Activé", fg="green")
        else:
            self.toggle_label.config(text="Désactivé", fg="red")


Game()